<?php
// $Id$

/**
 * @file
 *   Adds a "URL" widget to the Node Reference field.
 */

/**
 * Implementation of hook_theme().
 */
function nodereference_url_theme() {
  return array(
    'nodereference_url' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * Implementation of hook_form_alter().
 */
function nodereference_url_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'content_field_edit_form' && isset($form['#field']) && $form['#field']['widget']['type'] == 'nodereference_url') {
    // Hide settings that don't apply to this widget.
    $form['field']['multiple']['#type'] = 'value';
    $form['widget']['description']['#type'] = 'value';
  }
}

/**
 * Implementation of hook_widget_info().
 */
function nodereference_url_widget_info() {
  return array(
    'nodereference_url' => array(
      'label' => t('Reference from URL'),
      'field types' => array('nodereference'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_NONE,
      ),
    ),
  );
}

/**
 * Implementation of hook_link().
 */
function nodereference_url_link($type, $object, $teaser = FALSE) {
  $links = array();

  if ($type == 'node') {
    $fields = content_fields(NULL, $object->type);
    foreach ($fields as $field_name => $field) {
      if ($field['widget']['type'] == 'nodereference_url' && !empty($field['widget']['node_link']['enabled'])) {
        if ($field['referenceable_types'][$object->type]) {
          $links[$field_name] = array(
            'title' => $field['widget']['node_link']['title'],
            'href' => 'node/add/'. str_replace('_', '-', $field['type_name']) .'/'. $object->nid,
          );
          if (!empty($field['widget']['node_link']['hover_title'])) {
            $links[$field_name]['attributes']['title'] = $field['widget']['node_link']['hover_title'];
          }
        }
      }
    }
  }

  return $links;
}

/**
 * Implementation of FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 *
 * Autocomplete_path is not used by text_widget but other widgets can use it
 * (see nodereference and userreference).
 */
function nodereference_url_elements() {
  return array(
    'nodereference_url' => array(
      '#input' => TRUE,
      '#columns' => array('nid'),
      '#delta' => 0,
      '#process' => array('nodereference_url_process'),
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function nodereference_url_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();
      if ($widget['type'] == 'nodereference_url') {
        $form['fallback'] = array(
          '#type' => 'radios',
          '#title' => t('Fallback behavior'),
          '#options' => array(
            'page_not_found' => t('Display page not found error'),
            'select' => t('Use select list widget'),
            // TODO: Get autocomplete fallback working. Currently looses value on save.
            //'autocomplete' => t('Use autocomplete widget'),
            'leave_blank' => t('Leave the field blank'),
          ),
          '#default_value' => isset($widget['fallback']) ? $widget['fallback'] : 'page_not_found',
          '#description' => t('If no content is referenced in the URL, determine how the form should be handled.'),
          '#required' => TRUE,
          '#element_validate' => array('nodereference_url_fallback_validate'),
        );
        $form['node_link'] = array(
          '#tree' => TRUE,
          '#weight' => 2,
          '#element_validate' => array('nodereference_url_node_link_validate'),
        );
        $form['node_link']['enabled'] = array(
          '#type' => 'checkbox',
          '#title' => t('Create a link on referenceable content'),
          '#default_value' => isset($widget['node_link']['enabled']) ? $widget['node_link']['enabled'] : '1',
        );
        $form['node_link']['title'] = array(
          '#type' => 'textfield',
          '#title' => t('Link title'),
          '#default_value' => isset($widget['node_link']['title']) ? $widget['node_link']['title'] : '',
          '#description' => t('The title is the visible text for the link. This is required if you enable the content links.'),
        );
        $form['node_link']['hover_title'] = array(
          '#type' => 'textfield',
          '#title' => t('Link hover title'),
          '#default_value' => isset($widget['node_link']['hover_title']) ? $widget['node_link']['hover_title'] : '',
          '#description' => t('Text shown while hovering over the link.'),
        );
      }
      return $form;

    case 'save':
      return array('node_link', 'fallback');
  }
}

/**
 * Element validation function to ensure invalid options are not selected.
 */
function nodereference_url_fallback_validate($element, &$form_state) {
  if ($form_state['values']['required'] && $form_state['values']['fallback'] == 'leave_blank') {
    form_error($element, t('The fallback behavior cannot be left blank if this field is also required.'));
  }
}

/**
 * Element validation function that makes title required when creating a link.
 */
function nodereference_url_node_link_validate($element, &$form_state) {
  if ($form_state['values']['node_link']['enabled'] && empty($form_state['values']['node_link']['title'])) {
    form_error($element['title'], t('A link title must be specified if creating links on referenceable content.'));
  }
}

/**
 * Implementation of hook_widget().
 */
function nodereference_url_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  $element = array('#tree' => TRUE);

  if (isset($items[0]['nid']) && is_numeric($items[0]['nid'])) {
    $referenced_nid = $items[0]['nid'];
  }
  elseif (arg(0) == 'node' && arg(1) == 'add') {
    $referenced_nid = is_numeric(arg(3)) ? arg(3) : NULL;
  }

  if (!isset($referenced_nid)) {
    // Page not found error.
    if ($field['widget']['fallback'] == 'page_not_found') {
      drupal_set_message(t('To create a new @type, a referenced piece of content must be specified in the link you followed.', array('@type' => node_get_types('name', $field['type_name']))), 'error');
      drupal_not_found();
      exit();
    }
    // Fallback to select list.
    elseif ($field['widget']['fallback'] == 'select') {
      $element = array(
        '#type' => 'nodereference_select',
        '#default_value' => $items,
      );
    }
    // Fallback to autocomplete.
    elseif ($field['widget']['fallback'] == 'autocomplete') {
      $element = array(
        '#type' => 'nodereference_autocomplete',
        '#default_value' => isset($items[$delta]) ? $items[$delta] : NULL,
        '#value_callback' => 'nodereference_autocomplete_value',
      );
    }
    // Fallback to an empty field.
    else {
      $referenced_nid = '';
    }
  }

  if (isset($referenced_nid)) {
    $element['nid']['nid'] = array(
      '#title' => $field['widget']['label'],
      '#type' => 'nodereference_url',
      '#field_name' => $field['field_name'],
      '#default_value' => $referenced_nid,
    );
  }

  return $element;
}

/**
 * Process an individual element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function nodereference_url_process($element, $edit, $form_state, $form) {
  $field_key  = $element['#columns'][0];
  $field = $form['#field_info'][$element['#field_name']];

  if (isset($element['#value']) && is_numeric($element['#value'])) {
    $element['#display_title'] = _nodereference_titles($element['#value']);
  }
  else {
    $element['#display_title'] = t('Referenced content not found.');
  }

  $element['nid'] = array(
    '#type' => 'value',
    '#value' => isset($element['#value']) ? $element['#value'] : $element['#value'],
    '#parents' => $element['#parents'],
  );

  return $element;
}

/**
 * FAPI theme for an individual elements.
 *
 * The textfield or select is already rendered by the
 * textfield or select themes and the html output
 * lives in $element['#children']. Override this theme to
 * make custom changes to the output.
 *
 * $element['#field_name'] contains the field name
 * $element['#delta]  is the position of this element in the group
 */
function theme_nodereference_url($element) {
  return theme('form_element', $element, $element['#display_title']);
}
